// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: delete_user_by_uuid.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteUser = `-- name: DeleteUser :exec
DELETE 
FROM users 
WHERE 
    uuid = $1
`

func (q *Queries) DeleteUser(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, argUuid)
	return err
}
