// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: insert_user.sql

package database

import (
	"context"
)

const createUsers = `-- name: CreateUsers :one
INSERT INTO users (
	email
) 
VALUES (
	$1
) 
RETURNING id, created_at, uuid, email
`

func (q *Queries) CreateUsers(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, createUsers, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Uuid,
		&i.Email,
	)
	return i, err
}
