// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID        sql.NullInt64
	CreatedAt time.Time
	Uuid      uuid.UUID
	Email     string
}
