// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: select_user_by_uuid.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getUserByUUID = `-- name: GetUserByUUID :one
SELECT id, created_at, uuid, email
FROM users
WHERE
    uuid = $1
`

func (q *Queries) GetUserByUUID(ctx context.Context, argUuid uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUUID, argUuid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Uuid,
		&i.Email,
	)
	return i, err
}
