// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: update_user_by_uuid.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateUserByUUID = `-- name: UpdateUserByUUID :one
UPDATE users
SET
    email=$2
WHERE
    uuid=$1
RETURNING id, created_at, uuid, email
`

type UpdateUserByUUIDParams struct {
	Uuid  uuid.UUID
	Email string
}

func (q *Queries) UpdateUserByUUID(ctx context.Context, arg UpdateUserByUUIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserByUUID, arg.Uuid, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Uuid,
		&i.Email,
	)
	return i, err
}
